import GuthMaynardLemma116ClassAlgebra

open scoped BigOperators Real
open CGLProofDAG
open GuthMaynardLemma116
open GuthMaynardHeathBrownMajorant

noncomputable section
set_option maxHeartbeats 1600000
namespace GuthMaynardEnergy116GroupedMoment

/-- A finite Gram kernel generated by a phase family `f`. -/
def groupedGramKernel {α : Type*} (C : Finset α)
    (f : α → ℕ → ℂ) (n m : ℕ) : ℂ :=
  ∑ p ∈ C, f p n * star (f p m)

/-- The corresponding finite difference Dirichlet kernel for two class atoms. -/
def groupedDifferenceKernel {α : Type*} (C : Finset α)
    (f : α → ℕ → ℂ) (M : ℕ) (p q : α) : ℂ :=
  ∑ n ∈ Finset.Ioc M (2 * M), f p n * star (f q n)

private lemma finset_norm_sum_expand {ι : Type*} (s : Finset ι) (f : ι → ℂ) :
    (((‖∑ i ∈ s, f i‖ ^ 2 : ℝ) : ℂ)) =
      ∑ i ∈ s, ∑ j ∈ s, f i * star (f j) := by
  rw [Complex.sq_norm, ← Complex.mul_conj]
  change (∑ i ∈ s, f i) * star (∑ i ∈ s, f i) = _
  rw [star_sum, Finset.sum_mul]
  apply Finset.sum_congr rfl
  intro i hi
  rw [Finset.mul_sum]

private lemma reorder_four_factors {α : Type*} [DecidableEq α]
    (S : Finset ℕ) (C : Finset α) (F : ℕ → ℕ → α → α → ℂ) :
    (∑ n ∈ S, ∑ m ∈ S, ∑ p ∈ C, ∑ q ∈ C, F n m p q) =
      ∑ p ∈ C, ∑ q ∈ C, ∑ n ∈ S, ∑ m ∈ S, F n m p q := by
  have h1 (n : ℕ) :
      (∑ m ∈ S, ∑ p ∈ C, ∑ q ∈ C, F n m p q) =
        ∑ p ∈ C, ∑ q ∈ C, ∑ m ∈ S, F n m p q := by
    rw [Finset.sum_comm]
    apply Finset.sum_congr rfl
    intro p hp
    rw [Finset.sum_comm]
  rw [show (∑ n ∈ S, ∑ m ∈ S, ∑ p ∈ C, ∑ q ∈ C, F n m p q) =
      ∑ n ∈ S, ∑ p ∈ C, ∑ q ∈ C, ∑ m ∈ S, F n m p q by
    apply Finset.sum_congr rfl
    intro n hn
    exact h1 n]
  rw [Finset.sum_comm]
  apply Finset.sum_congr rfl
  intro p hp
  rw [Finset.sum_comm]

/-- Exact finite Gram identity on the open-left dyadic block.  It is purely
finite algebra and makes no analytic estimate. -/
theorem groupedGramKernel_norm_square_Ioc
    {α : Type*} [DecidableEq α]
    (C : Finset α) (f : α → ℕ → ℂ) (M : ℕ) :
    (∑ n ∈ Finset.Ioc M (2 * M),
      ∑ m ∈ Finset.Ioc M (2 * M),
        ‖groupedGramKernel C f n m‖ ^ 2) =
      ∑ p ∈ C, ∑ q ∈ C,
        ‖groupedDifferenceKernel C f M p q‖ ^ 2 := by
  apply Complex.ofReal_injective
  simp_rw [Complex.ofReal_sum]
  simp_rw [groupedGramKernel, groupedDifferenceKernel,
    finset_norm_sum_expand]
  rw [reorder_four_factors]
  apply Finset.sum_congr rfl
  intro p hp
  apply Finset.sum_congr rfl
  intro q hq
  simp only [star_mul, star_star]
  apply Finset.sum_congr rfl
  intro n hn
  apply Finset.sum_congr rfl
  intro m hm
  ring

/-- Dirichlet phases for an ordered difference pair. -/
def orderedDifferencePhase (p : ℝ × ℝ) (n : ℕ) : ℂ :=
  dirichletPhase n (p.1 - p.2)

def orderedDifferenceKernel116 (M : ℕ) (delta : ℝ) : ℂ :=
  ∑ n ∈ Finset.Ioc M (2 * M),
    Complex.exp (Complex.I * (((delta * Real.log (n : ℝ) : ℝ) : ℂ)))

theorem orderedDifferenceKernel116_eq_dirichletPolynomial
    (M : ℕ) (delta : ℝ) :
    orderedDifferenceKernel116 M delta =
      dirichletPolynomial (fun _ => (1 : ℂ)) M delta := by
  unfold orderedDifferenceKernel116 dirichletPolynomial
  apply Finset.sum_congr rfl
  intro n hn
  simp only [one_mul]
  congr 1
  push_cast
  ring

def ratioPairDifferencePhase116 (v : ℝ) (p : ℝ × ℝ) : ℂ :=
  Complex.exp (Complex.I * (((p.1 * Real.log |v| : ℝ) : ℂ))) *
    star (Complex.exp (Complex.I * (((p.2 * Real.log |v| : ℝ) : ℝ) : ℂ)))

def activePairClass116 (W : Finset ℝ) (j : ℕ) : Finset (ℝ × ℝ) :=
  (W.product W).filter fun p =>
    Nat.log2 (floorDifferenceMultiplicity W (floorDifference p)) = j

def groupedDifferenceField116 (W : Finset ℝ) (j : ℕ) (v : ℝ) : ℂ :=
  ∑ p ∈ activePairClass116 W j, ratioPairDifferencePhase116 v p

private theorem ratioPairDifferencePhase116_eq_orderedDifferencePhase_mul_star
    (p : ℝ × ℝ) {n m : ℕ} (hn : 0 < n) (hm : 0 < m) :
    ratioPairDifferencePhase116 ((n : ℝ) / (m : ℝ)) p =
      orderedDifferencePhase p n * star (orderedDifferencePhase p m) := by
  unfold ratioPairDifferencePhase116 orderedDifferencePhase
  have hnR : (0 : ℝ) < n := by exact_mod_cast hn
  have hmR : (0 : ℝ) < m := by exact_mod_cast hm
  rw [abs_of_pos (div_pos hnR hmR), Real.log_div hnR.ne' hmR.ne']
  have hstar (x : ℝ) :
      star (Complex.exp (Complex.I * ((x : ℝ) : ℂ))) =
        Complex.exp (-Complex.I * ((x : ℝ) : ℂ)) := by
    rw [show star (Complex.exp (Complex.I * ((x : ℝ) : ℂ))) =
        Complex.exp (star (Complex.I * ((x : ℝ) : ℂ))) by
      exact (Complex.exp_conj _).symm]
    congr 1
    change (starRingEnd ℂ) (Complex.I * ((x : ℝ) : ℂ)) = _
    rw [map_mul, Complex.conj_I, Complex.conj_ofReal]
  unfold dirichletPhase
  have hstar' (x : ℝ) :
      star (Complex.exp ((((x : ℝ) : ℂ) * Complex.I))) =
        Complex.exp (-Complex.I * ((x : ℝ) : ℂ)) := by
    rw [show star (Complex.exp ((((x : ℝ) : ℂ) * Complex.I))) =
        Complex.exp (star (((x : ℝ) : ℂ) * Complex.I)) by
      exact (Complex.exp_conj _).symm]
    congr 1
    change (starRingEnd ℂ) (((x : ℝ) : ℂ) * Complex.I) = _
    rw [map_mul, Complex.conj_ofReal, Complex.conj_I]
    ring_nf
  rw [hstar, hstar']
  rw [← Complex.exp_add]
  rw [← Complex.exp_add]
  congr 1
  push_cast
  ring

/-- The source-facing grouped field built from ordered-difference phases. -/
def orderedDifferenceGroupedField (C : Finset (ℝ × ℝ)) (n m : ℕ) : ℂ :=
  groupedGramKernel C orderedDifferencePhase n m

/-- Specialization of the finite Gram identity to ordered-difference phases.
The right side is indexed by the active pair class and is the exact finite
object to which the shifted local `L²` estimate is applied. -/
theorem orderedDifferenceGroupedField_norm_square_Ioc
    (C : Finset (ℝ × ℝ)) (M : ℕ) :
    (∑ n ∈ Finset.Ioc M (2 * M),
      ∑ m ∈ Finset.Ioc M (2 * M),
        ‖orderedDifferenceGroupedField C n m‖ ^ 2) =
      ∑ p ∈ C, ∑ q ∈ C,
        ‖groupedDifferenceKernel C orderedDifferencePhase M p q‖ ^ 2 := by
  exact groupedGramKernel_norm_square_Ioc C orderedDifferencePhase M

theorem groupedDifferenceKernel_eq_orderedDifferenceKernel116
    (C : Finset (ℝ × ℝ)) (M : ℕ) (p q : ℝ × ℝ) :
    groupedDifferenceKernel C orderedDifferencePhase M p q =
      orderedDifferenceKernel116 M ((p.1 - p.2) - (q.1 - q.2)) := by
  unfold groupedDifferenceKernel orderedDifferenceKernel116 orderedDifferencePhase
  apply Finset.sum_congr rfl
  intro n hn
  rw [dirichletPhase_difference]
  congr 2
  push_cast
  ring

theorem orderedDifferenceGroupedField_norm_square_Ioc_eq_differenceKernel
    (C : Finset (ℝ × ℝ)) (M : ℕ) :
    (∑ n ∈ Finset.Ioc M (2 * M),
      ∑ m ∈ Finset.Ioc M (2 * M),
        ‖orderedDifferenceGroupedField C n m‖ ^ 2) =
      ∑ p ∈ C, ∑ q ∈ C,
        ‖orderedDifferenceKernel116 M ((p.1 - p.2) - (q.1 - q.2))‖ ^ 2 := by
  rw [orderedDifferenceGroupedField_norm_square_Ioc C M]
  apply Finset.sum_congr rfl
  intro p hp
  apply Finset.sum_congr rfl
  intro q hq
  rw [groupedDifferenceKernel_eq_orderedDifferenceKernel116 C M p q]

theorem groupedDifferenceField116_norm_square_Ioc_eq_differenceKernel
    (M : ℕ) (W : Finset ℝ) (j : ℕ) (hM : 1 ≤ M) :
    (∑ n ∈ Finset.Ioc M (2 * M),
      ∑ m ∈ Finset.Ioc M (2 * M),
        ‖groupedDifferenceField116 W j ((n : ℝ) / (m : ℝ))‖ ^ 2) =
      ∑ p ∈ activePairClass116 W j, ∑ q ∈ activePairClass116 W j,
        ‖orderedDifferenceKernel116 M ((p.1 - p.2) - (q.1 - q.2))‖ ^ 2 := by
  let C := activePairClass116 W j
  have hfield (n m : ℕ)
      (hn : n ∈ Finset.Ioc M (2 * M))
      (hm : m ∈ Finset.Ioc M (2 * M)) :
      groupedDifferenceField116 W j ((n : ℝ) / (m : ℝ)) =
        orderedDifferenceGroupedField C n m := by
    unfold groupedDifferenceField116 orderedDifferenceGroupedField
    apply Finset.sum_congr rfl
    intro p hp
    apply ratioPairDifferencePhase116_eq_orderedDifferencePhase_mul_star
    · exact (lt_of_lt_of_le Nat.zero_lt_one hM).trans
        (Finset.mem_Ioc.mp hn).1
    · exact (lt_of_lt_of_le Nat.zero_lt_one hM).trans
        (Finset.mem_Ioc.mp hm).1
  rw [show
      (∑ n ∈ Finset.Ioc M (2 * M),
        ∑ m ∈ Finset.Ioc M (2 * M),
          ‖groupedDifferenceField116 W j ((n : ℝ) / (m : ℝ))‖ ^ 2) =
        ∑ n ∈ Finset.Ioc M (2 * M),
          ∑ m ∈ Finset.Ioc M (2 * M),
            ‖orderedDifferenceGroupedField C n m‖ ^ 2 by
    apply Finset.sum_congr rfl
    intro n hn
    apply Finset.sum_congr rfl
    intro m hm
    rw [hfield n m hn hm]]
  exact orderedDifferenceGroupedField_norm_square_Ioc_eq_differenceKernel C M

end GuthMaynardEnergy116GroupedMoment

#print axioms GuthMaynardEnergy116GroupedMoment.groupedGramKernel_norm_square_Ioc
#print axioms GuthMaynardEnergy116GroupedMoment.orderedDifferenceGroupedField_norm_square_Ioc
#print axioms GuthMaynardEnergy116GroupedMoment.orderedDifferenceGroupedField_norm_square_Ioc_eq_differenceKernel
#print axioms GuthMaynardEnergy116GroupedMoment.groupedDifferenceField116_norm_square_Ioc_eq_differenceKernel
