import AppendixA5ClosedLocalZeroCount

/-!
# Restricting a global zero rectangle to a unit ordinate window

This module connects the multiplicities used by the truncated explicit
formula to the already certified closed local zero count.  The two counts use
different compact rectangles, so the proof explicitly transports the
meromorphic divisor rather than treating multiplicity as an arbitrary weight.
-/

namespace MAPPaperWindowVKBypass

open Complex Set
open scoped BigOperators
open DirichletZeros MAPMellinDetectorLeaf MAPLocalZeroWindow

noncomputable section

variable {q : ℕ} [NeZero q]

/-- The zeros exposed in a global height rectangle whose ordinates lie in one
closed unit interval. -/
def globalUnitWindowSupport (χ : DirichletCharacter ℂ q)
    (σ T t : ℝ) : Finset ℂ :=
  (zeroSupport χ σ T).filter fun ρ => t ≤ ρ.im ∧ ρ.im ≤ t + 1

private theorem mem_local_rectangle_of_mem_globalUnitWindowSupport
    (χ : DirichletCharacter ℂ q) {σ T t : ℝ} {ρ : ℂ}
    (hρ : ρ ∈ globalUnitWindowSupport χ σ T t) :
    ρ ∈ zeroRectangle σ (windowHeight t) := by
  have hg : ρ ∈ zeroSupport χ σ T := (Finset.mem_filter.mp hρ).1
  have hr : ρ ∈ zeroRectangle σ T :=
    (zeroDivisor χ σ T).supportWithinDomain
      ((zeroSupport_mem_iff χ σ T ρ).mp hg)
  have hi := (Finset.mem_filter.mp hρ).2
  rw [zeroRectangle, Complex.mem_reProdIm] at hr ⊢
  refine ⟨hr.1, ?_⟩
  unfold windowHeight
  constructor
  · have htlow : -|t| ≤ t := neg_abs_le t
    linarith [hi.1]
  · have htup : t ≤ |t| := le_abs_self t
    linarith [hi.2]

/-- The global slice is literally contained in the local Jensen support. -/
theorem globalUnitWindowSupport_subset_closed
    (χ : DirichletCharacter ℂ q) (σ T t : ℝ) :
    globalUnitWindowSupport χ σ T t ⊆
      closedUnitWindowSupport χ σ t := by
  intro ρ hρ
  rw [closedUnitWindowSupport, Finset.mem_filter]
  have hlocal := mem_local_rectangle_of_mem_globalUnitWindowSupport χ hρ
  have hglobal : ρ ∈ zeroSupport χ σ T := (Finset.mem_filter.mp hρ).1
  have hglobalRect : ρ ∈ zeroRectangle σ T :=
    (zeroDivisor χ σ T).supportWithinDomain
      ((zeroSupport_mem_iff χ σ T ρ).mp hglobal)
  have hneGlobal := (zeroSupport_mem_iff χ σ T ρ).mp hglobal
  have hneLocal : zeroDivisor χ σ (windowHeight t) ρ ≠ 0 := by
    rw [zeroDivisor_apply_eq_of_mem_rectangles χ hlocal hglobalRect]
    exact hneGlobal
  exact ⟨(zeroSupport_mem_iff χ σ (windowHeight t) ρ).mpr hneLocal,
    (Finset.mem_filter.mp hρ).2⟩

/-- Rectangle-independent analytic multiplicity on the global unit slice. -/
theorem zeroMultiplicity_global_eq_local
    (χ : DirichletCharacter ℂ q) {σ T t : ℝ} {ρ : ℂ}
    (hρ : ρ ∈ globalUnitWindowSupport χ σ T t) :
    zeroMultiplicity χ σ T ρ =
      zeroMultiplicity χ σ (windowHeight t) ρ := by
  have hglobal : ρ ∈ zeroSupport χ σ T := (Finset.mem_filter.mp hρ).1
  have hglobalRect : ρ ∈ zeroRectangle σ T :=
    (zeroDivisor χ σ T).supportWithinDomain
      ((zeroSupport_mem_iff χ σ T ρ).mp hglobal)
  exact zeroMultiplicity_eq_of_mem_rectangles χ
    hglobalRect
    (mem_local_rectangle_of_mem_globalUnitWindowSupport χ hρ)

/-- A unit slice of the global explicit-formula zero list is bounded by the
certified local count, with analytic multiplicity on both sides. -/
theorem globalUnitWindowCount_le_closed
    (χ : DirichletCharacter ℂ q) (σ T t : ℝ) :
    (∑ ρ ∈ globalUnitWindowSupport χ σ T t,
        zeroMultiplicity χ σ T ρ) ≤
      closedUnitWindowCount χ σ t := by
  unfold closedUnitWindowCount
  calc
    (∑ ρ ∈ globalUnitWindowSupport χ σ T t,
        zeroMultiplicity χ σ T ρ) =
      ∑ ρ ∈ globalUnitWindowSupport χ σ T t,
        zeroMultiplicity χ σ (windowHeight t) ρ := by
          apply Finset.sum_congr rfl
          intro ρ hρ
          exact zeroMultiplicity_global_eq_local χ hρ
    _ ≤ ∑ ρ ∈ closedUnitWindowSupport χ σ t,
        zeroMultiplicity χ σ (windowHeight t) ρ :=
      Finset.sum_le_sum_of_subset_of_nonneg
        (globalUnitWindowSupport_subset_closed χ σ T t)
        (fun _ _ _ => Nat.zero_le _)

/-- Premise-free logarithmic bound for every global unit slice of a
nonprincipal character. -/
theorem globalUnitWindowCount_le_log
    (χ : DirichletCharacter ℂ q) (hχ : χ ≠ 1)
    {σ T t : ℝ} (hσ : 1 / 2 ≤ σ) :
    (∑ ρ ∈ globalUnitWindowSupport χ σ T t,
        (zeroMultiplicity χ σ T ρ : ℝ)) ≤
      153 * Real.log (arithmeticScale q t) := by
  have hnat := globalUnitWindowCount_le_closed χ σ T t
  have hcast :
      (∑ ρ ∈ globalUnitWindowSupport χ σ T t,
          (zeroMultiplicity χ σ T ρ : ℝ)) ≤
        (closedUnitWindowCount χ σ t : ℝ) := by
    exact_mod_cast hnat
  exact hcast.trans
    (MAPAppendixA5ClosedLocalZeroCount.certifiedAppendixA5ClosedLocalZeroCount_nonprincipal
      χ hχ hσ)

/-- The square-summable ordinate kernel generated by the complex interval
average. -/
def ordinateSquareKernel (γ : ℝ) : ℝ :=
  1 / (1 + |γ|) ^ 2

/-- On a positive unit shell, the ordinate kernel is bounded by its value at
the left endpoint. -/
theorem ordinateSquareKernel_le_shellCap
    {t γ : ℝ} (ht : 0 ≤ t) (hγ : t ≤ γ) :
    ordinateSquareKernel γ ≤ 1 / (1 + t) ^ 2 := by
  have hbase : 1 + t ≤ 1 + |γ| := by
    linarith [hγ.trans (le_abs_self γ)]
  have hsq : (1 + t) ^ 2 ≤ (1 + |γ|) ^ 2 := by
    exact pow_le_pow_left₀ (by linarith) hbase 2
  unfold ordinateSquareKernel
  exact one_div_le_one_div_of_le (sq_pos_of_pos (by linarith)) hsq

/-- A literal kernel-weighted high-ordinate shell bound obtained from the
certified local zero count.  This is the deterministic summation primitive
used after the complex-average `1/|gamma|` gain is squared. -/
theorem globalUnitWindow_ordinateSquareKernel_le_log
    (χ : DirichletCharacter ℂ q) (hχ : χ ≠ 1)
    {σ T t : ℝ} (hσ : 1 / 2 ≤ σ) (ht : 0 ≤ t) :
    (∑ ρ ∈ globalUnitWindowSupport χ σ T t,
        (zeroMultiplicity χ σ T ρ : ℝ) *
          ordinateSquareKernel ρ.im) ≤
      (1 / (1 + t) ^ 2) *
        (153 * Real.log (arithmeticScale q t)) := by
  calc
    (∑ ρ ∈ globalUnitWindowSupport χ σ T t,
        (zeroMultiplicity χ σ T ρ : ℝ) *
          ordinateSquareKernel ρ.im) ≤
      ∑ ρ ∈ globalUnitWindowSupport χ σ T t,
        (zeroMultiplicity χ σ T ρ : ℝ) *
          (1 / (1 + t) ^ 2) := by
            apply Finset.sum_le_sum
            intro ρ hρ
            apply mul_le_mul_of_nonneg_left
            · exact ordinateSquareKernel_le_shellCap ht
                (Finset.mem_filter.mp hρ).2.1
            · exact Nat.cast_nonneg _
    _ = (1 / (1 + t) ^ 2) *
        (∑ ρ ∈ globalUnitWindowSupport χ σ T t,
          (zeroMultiplicity χ σ T ρ : ℝ)) := by
            rw [Finset.mul_sum]
            apply Finset.sum_congr rfl
            intro ρ hρ
            ring
    _ ≤ (1 / (1 + t) ^ 2) *
        (153 * Real.log (arithmeticScale q t)) := by
          apply mul_le_mul_of_nonneg_left
            (globalUnitWindowCount_le_log χ hχ hσ)
          positivity

end
end MAPPaperWindowVKBypass

#print axioms MAPPaperWindowVKBypass.globalUnitWindowSupport_subset_closed
#print axioms MAPPaperWindowVKBypass.globalUnitWindowCount_le_closed
#print axioms MAPPaperWindowVKBypass.globalUnitWindowCount_le_log
#print axioms MAPPaperWindowVKBypass.globalUnitWindow_ordinateSquareKernel_le_log
