import MRTWholeLineEquation81FromEquation82

/-!
# Deterministic packet-superposition to correlation-bilinear inequality

This is the exact Hilbert-space/Fubini bridge between the square of a packet
superposition and the absolute packet-correlation bilinear used in MRT (81).
It contains no number-theoretic estimate.
-/

namespace MAPMRTEquation79PacketBilinearCore

open MeasureTheory
open MAPMRTPacketEquation82 MAPMRTWholeLineEquation81FromEquation82

noncomputable section

/-- The packet superposition generated by a scalar frequency amplitude. -/
def packetSuperposition (A : ℝ → ℂ) (J : ℝ → ℝ → ℂ) (x : ℝ) : ℂ :=
  ∫ t : ℝ, A t * J t x

/-- The literal three-variable kernel used to expand the squared `L²` norm. -/
def packetEnergyTripleKernel
    (A : ℝ → ℂ) (J : ℝ → ℝ → ℂ) (z : ℝ × (ℝ × ℝ)) : ℂ :=
  (A z.2.1 * J z.2.1 z.1) * star (A z.2.2 * J z.2.2 z.1)

/-- Exact Fubini expansion of packet-superposition energy into packet
correlations.  The sole hypotheses are the Bochner-integrability conditions
needed for the three legal Fubini/product-integral steps. -/
theorem integral_norm_sq_packetSuperposition_eq_correlation
    {A : ℝ → ℂ} {J : ℝ → ℝ → ℂ}
    (hTriple : Integrable (packetEnergyTripleKernel A J)
      (volume.prod (volume.prod volume)))
    (hCorr : Integrable (Function.uncurry (fun t t' : ℝ ↦
      A t * star (A t') * packetCorrelation J t t'))
      (volume.prod volume)) :
    ((∫ x : ℝ, ‖packetSuperposition A J x‖ ^ 2 : ℝ) : ℂ) =
      ∫ z : ℝ × ℝ,
        A z.1 * star (A z.2) * packetCorrelation J z.1 z.2 := by
  have hTripleX : ∀ᶠ x : ℝ in ae volume,
      Integrable (Function.uncurry (fun t t' : ℝ ↦
        packetEnergyTripleKernel A J (x, (t, t'))))
        (volume.prod volume) := hTriple.prod_right_ae
  have hTripleTT : ∀ᶠ z : ℝ × ℝ in ae (volume.prod volume),
      Integrable (fun x : ℝ ↦ packetEnergyTripleKernel A J (x, z)) := by
    have hs := hTriple.swap
    simpa [Function.comp_def] using hs.prod_right_ae
  have hPair : ∀ᶠ x : ℝ in ae volume,
      (packetSuperposition A J x) * star (packetSuperposition A J x) =
        ∫ z : ℝ × ℝ, packetEnergyTripleKernel A J (x, z) := by
    filter_upwards [hTripleX] with x hx
    have hxLeft : Integrable (fun t : ℝ ↦
        ∫ t' : ℝ, packetEnergyTripleKernel A J (x, (t, t'))) :=
      hx.integral_prod_left
    have hxSections : ∀ᶠ t : ℝ in ae volume,
        Integrable (fun t' : ℝ ↦
          packetEnergyTripleKernel A J (x, (t, t'))) := hx.prod_right_ae
    unfold packetSuperposition
    change (∫ t : ℝ, A t * J t x) *
      (starRingEnd ℂ) (∫ t : ℝ, A t * J t x) = _
    rw [← integral_conj]
    rw [← integral_mul_const]
    calc
      (∫ t : ℝ, A t * J t x *
          ∫ t' : ℝ, (starRingEnd ℂ) (A t' * J t' x)) =
          ∫ t : ℝ, ∫ t' : ℝ,
            packetEnergyTripleKernel A J (x, (t, t')) := by
        apply integral_congr_ae
        filter_upwards [hxSections] with t ht
        rw [← integral_const_mul]
        apply integral_congr_ae
        filter_upwards with t'
        unfold packetEnergyTripleKernel
        rfl
      _ = ∫ z : ℝ × ℝ,
          packetEnergyTripleKernel A J (x, (z.1, z.2)) :=
        integral_integral hx
      _ = ∫ z : ℝ × ℝ, packetEnergyTripleKernel A J (x, z) := rfl
  have hEnergyComplex : Integrable (fun x : ℝ ↦
      (packetSuperposition A J x) * star (packetSuperposition A J x)) := by
    have hleft := hTriple.integral_prod_left
    apply hleft.congr
    filter_upwards [hPair] with x hx
    exact hx.symm
  have hEnergyReal : Integrable (fun x : ℝ ↦
      ‖packetSuperposition A J x‖ ^ 2) := by
    apply hEnergyComplex.norm.congr
    filter_upwards with x
    simp [pow_two]
  -- Expand the square, swap `x` past `(t,t')`, then recognize correlation.
  have hswap := integral_integral_swap
    (f := fun x (z : ℝ × ℝ) ↦ packetEnergyTripleKernel A J (x, z)) hTriple
  have hCorrPoint : ∀ᶠ z : ℝ × ℝ in ae (volume.prod volume),
      (∫ x : ℝ, packetEnergyTripleKernel A J (x, z)) =
        A z.1 * star (A z.2) * packetCorrelation J z.1 z.2 := by
    filter_upwards [hTripleTT] with z hz
    unfold packetEnergyTripleKernel packetCorrelation
    rw [← integral_const_mul]
    apply integral_congr_ae
    filter_upwards with x
    rw [Complex.star_def, map_mul]
    ring
  calc
    ((∫ x : ℝ, ‖packetSuperposition A J x‖ ^ 2 : ℝ) : ℂ) =
        ∫ x : ℝ,
          (packetSuperposition A J x) * star (packetSuperposition A J x) := by
      calc
        ((∫ x : ℝ, ‖packetSuperposition A J x‖ ^ 2 : ℝ) : ℂ) =
            ∫ x : ℝ, ((‖packetSuperposition A J x‖ ^ 2 : ℝ) : ℂ) :=
          integral_ofReal.symm
        _ = _ := by
          apply integral_congr_ae
          filter_upwards with x
          simpa using (RCLike.mul_conj (packetSuperposition A J x)).symm
    _ = ∫ x : ℝ, ∫ z : ℝ × ℝ,
          packetEnergyTripleKernel A J (x, z) := by
      apply integral_congr_ae
      exact hPair
    _ = ∫ z : ℝ × ℝ, ∫ x : ℝ,
          packetEnergyTripleKernel A J (x, z) := hswap
    _ = ∫ z : ℝ × ℝ,
          A z.1 * star (A z.2) * packetCorrelation J z.1 z.2 := by
      apply integral_congr_ae
      exact hCorrPoint

/-- Taking absolute values in the exact energy expansion yields the MRT
packet-correlation bilinear. -/
theorem ofReal_integral_norm_sq_packetSuperposition_le_bilinear
    {A : ℝ → ℂ} {J : ℝ → ℝ → ℂ}
    (hTriple : Integrable (packetEnergyTripleKernel A J)
      (volume.prod (volume.prod volume)))
    (hCorr : Integrable (Function.uncurry (fun t t' : ℝ ↦
      A t * star (A t') * packetCorrelation J t t'))
      (volume.prod volume)) :
    ENNReal.ofReal (∫ x : ℝ, ‖packetSuperposition A J x‖ ^ 2) ≤
      packetCorrelationBilinear J (fun t ↦ ENNReal.ofReal ‖A t‖) := by
  have hEq := integral_norm_sq_packetSuperposition_eq_correlation hTriple hCorr
  have hNonneg : 0 ≤ ∫ x : ℝ, ‖packetSuperposition A J x‖ ^ 2 :=
    integral_nonneg fun x ↦ sq_nonneg _
  have hNorm : (∫ x : ℝ, ‖packetSuperposition A J x‖ ^ 2) ≤
      ‖∫ z : ℝ × ℝ,
        A z.1 * star (A z.2) * packetCorrelation J z.1 z.2‖ := by
    have hn := congrArg norm hEq
    calc
      (∫ x : ℝ, ‖packetSuperposition A J x‖ ^ 2) =
          ‖((∫ x : ℝ, ‖packetSuperposition A J x‖ ^ 2 : ℝ) : ℂ)‖ := by
        simp [Complex.norm_real, Real.norm_eq_abs, abs_of_nonneg hNonneg]
      _ = _ := hn
      _ ≤ _ := le_rfl
  have hInt : ‖∫ z : ℝ × ℝ,
        A z.1 * star (A z.2) * packetCorrelation J z.1 z.2‖ ≤
      ∫ z : ℝ × ℝ,
        ‖A z.1‖ * ‖A z.2‖ * ‖packetCorrelation J z.1 z.2‖ := by
    calc
      _ ≤ ∫ z : ℝ × ℝ,
          ‖A z.1 * star (A z.2) * packetCorrelation J z.1 z.2‖ :=
        norm_integral_le_integral_norm _
      _ = _ := by
        apply integral_congr_ae
        filter_upwards with z
        simp [norm_mul]
  have hReal := hNorm.trans hInt
  unfold packetCorrelationBilinear
  have hqInt : Integrable (fun z : ℝ × ℝ ↦
      ‖A z.1‖ * ‖A z.2‖ * ‖packetCorrelation J z.1 z.2‖) := by
    simpa [Function.uncurry] using! hCorr.norm
  calc
    ENNReal.ofReal (∫ x : ℝ, ‖packetSuperposition A J x‖ ^ 2) ≤
        ENNReal.ofReal (∫ z : ℝ × ℝ,
          ‖A z.1‖ * ‖A z.2‖ * ‖packetCorrelation J z.1 z.2‖) :=
      ENNReal.ofReal_le_ofReal hReal
    _ = ∫⁻ z : ℝ × ℝ,
        ENNReal.ofReal
          (‖A z.1‖ * ‖A z.2‖ * ‖packetCorrelation J z.1 z.2‖) :=
      ofReal_integral_eq_lintegral_ofReal hqInt
        (Filter.Eventually.of_forall fun z ↦ by positivity)
    _ = ∫⁻ z : ℝ × ℝ,
        ENNReal.ofReal ‖A z.1‖ * ENNReal.ofReal ‖A z.2‖ *
          ENNReal.ofReal ‖packetCorrelation J z.1 z.2‖ := by
      apply lintegral_congr
      intro z
      rw [ENNReal.ofReal_mul
          (mul_nonneg (norm_nonneg _) (norm_nonneg _)),
        ENNReal.ofReal_mul (norm_nonneg _)]

#print axioms integral_norm_sq_packetSuperposition_eq_correlation
#print axioms ofReal_integral_norm_sq_packetSuperposition_le_bilinear

end
end MAPMRTEquation79PacketBilinearCore
